name: CI/CD Workflow Github
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.101"
      - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/opencover.xml
      - run: dotnet publish ./Johann.DeAlmeida.FeatureMatching.Console/Johann.DeAlmeida.FeatureMatching.Console.csproj --self-contained true --output ./win-x64/FeatureMatching -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Publish win-x64 FeatureMatching
          path: ./win-x64/FeatureMatching
